config/routes.rb
Rails.application.routes.draw do
  get 'conversation/index'

  get 'conversation/show'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'conversation#index'
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
	belongs_to :user1, class_name: 'User'
	belongs_to :user2, class_name: 'User'
	has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :conversation, optional: true
  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/conversation_controller.rb
class ConversationController < ApplicationController
  def index
  	@users = User.all
  	@conversations = Conversation.all
  end

  def show
  	@other_user = User.find(other_user_param[:other_user_id])
  	@conversation = Conversation.where(["user1_id = ? AND user2_id = ?",current_user.id, @other_user.id]).first
  	if @conversation.nil?
  		@conversation = Conversation.where(["user2_id = ? AND user1_id = ?",current_user.id, @other_user.id]).first
  	end
  	if @conversation.nil?
  		@conversation = Conversation.new()
  		@conversation.user1 = current_user
  		@conversation.user2 = @other_user
  		@conversation.save
  	end
  	@messages = @conversation.messages.reverse
  end
  private
  	# Use callbacks to share common setup or constraints between actions.
  	def other_user_param
  		params.permit(:other_user_id)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
end

app/views/conversation/index.html.erb
<h1>Conversation</h1>
<% @conversations.each do |conversation| %>

<% end %>
<h2>User List</h2>
<% @users.each do |user| %>
	<p><%= link_to user.email, conversation_show_path(other_user_id: user.id) %>
<% end %>

app/views/conversation/show.html.erb
<h1>Conversation with <%= @other_user.email %></h1>
<form> 
	<label>Say something:</label><br>
	<input type="text" data-behavior="conversation_speaker"> 
</form>
<div id="messages"  data-conversation-id=<%= @conversation.id %>>
	<%= render @messages %> 
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatModule</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	 <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Chat Module</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
          	<% if user_signed_in? %>
          		<li><a href="#">Hello, <%= current_user.email %></a></li>
          		<li><%= link_to 'Log Out', destroy_user_session_path, :method => :delete %></li>
            <% else %>
            	<li><%= link_to 'Sign Up', new_user_registration_path %></li>
            	<li><%= link_to 'Log In', new_user_session_path %></li>
          	<% end %>
            <li><%= link_to 'Home', root_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
       <%= yield %>
    </div> <!-- /container -->
  </body>
</html>

app/views/messages/_message.html.erb
<div class=“message”>
  <p><%= message.body %></p>
</div>